from django.db import models

# Create your models here.
class Customer(models.Model):
    ListID = models.CharField(max_length=255, primary_key=True)
    TimeCreated = models.TextField(null=True, blank=True)
    TimeModified = models.TextField(null=True, blank=True)
    EditSequence = models.TextField(null=True, blank=True)
    Name  = models.TextField(null=True, blank=True)
    FullName = models.TextField(null=True, blank=True)
    IsActive = models.TextField(null=True, blank=True)
    CompanyName = models.TextField(null=True, blank=True)
    Salutation = models.TextField(null=True, blank=True)
    FirstName = models.TextField(null=True, blank=True)
    MiddleName = models.TextField(null=True, blank=True)
    LastName = models.TextField(null=True, blank=True)
    JobTitle = models.TextField(null=True, blank=True)
    BillAddressAddr1 = models.TextField(null=True, blank=True)
    BillAddressAddr2 = models.TextField(null=True, blank=True)
    BillAddressAddr3 = models.TextField(null=True, blank=True)
    BillAddressAddr4 = models.TextField(null=True, blank=True)
    BillAddressAddr5 = models.TextField(null=True, blank=True)
    BillAddressCity = models.TextField(null=True, blank=True)
    BillAddressState = models.TextField(null=True, blank=True)
    BillAddressProvince = models.TextField(null=True, blank=True)
    BillAddressCountry = models.TextField(null=True, blank=True)
    BillAddressPostalCode = models.TextField(null=True, blank=True)
    BillAddressNote = models.TextField(null=True, blank=True)
    BillAddressBlockAddr1 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr2 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr3 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr4 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr5 = models.TextField(null=True, blank=True)
    ShipAddressAddr1 = models.TextField(null=True, blank=True)
    ShipAddressAddr2 = models.TextField(null=True, blank=True)
    ShipAddressAddr3 = models.TextField(null=True, blank=True)
    ShipAddressAddr4 = models.TextField(null=True, blank=True)
    ShipAddressAddr5 = models.TextField(null=True, blank=True)
    ShipAddressCity = models.TextField(null=True, blank=True)
    ShipAddressState = models.TextField(null=True, blank=True)
    ShipAddressProvince = models.TextField(null=True, blank=True)
    ShipAddressCountry = models.TextField(null=True, blank=True)
    ShipAddressPostalCode = models.TextField(null=True, blank=True)
    ShipAddressNote = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr1 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr2 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr3 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr4 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr5 = models.TextField(null=True, blank=True)
    Phone = models.TextField(null=True, blank=True)
    AltPhone = models.TextField(null=True, blank=True)
    Fax = models.TextField(null=True, blank=True)
    Email = models.TextField(null=True, blank=True)
    Cc = models.TextField(null=True, blank=True)
    Contact = models.TextField(null=True, blank=True)
    AltContact = models.TextField(null=True, blank=True)
    CustomerTypeRefListID = models.TextField(null=True, blank=True)
    CustomerTypeRefFullName = models.TextField(null=True, blank=True)
    TermsRefListID = models.TextField(null=True, blank=True)
    TermsRefFullName = models.TextField(null=True, blank=True)
    SalesRepRefListID = models.TextField(null=True, blank=True)
    SalesRepRefFullName = models.TextField(null=True, blank=True)
    Balance = models.TextField(null=True, blank=True)
    TotalBalance = models.TextField(null=True, blank=True)
    OpenBalance = models.TextField(null=True, blank=True)
    SalesTaxCodeRefListID = models.TextField(null=True, blank=True)
    SalesTaxCodeRefFullName = models.TextField(null=True, blank=True)
    TaxCodeRefListID = models.TextField(null=True, blank=True)
    TaxCodeRefFullName = models.TextField(null=True, blank=True)
    ItemSalesTaxRefListID = models.TextField(null=True, blank=True)
    ItemSalesTaxRefFullName = models.TextField(null=True, blank=True)
    SalesTaxCountry = models.TextField(null=True, blank=True)
    ResaleNumber = models.TextField(null=True, blank=True)
    AccountNumber = models.TextField(null=True, blank=True)
    BusinessNumber = models.TextField(null=True, blank=True)
    CreditLimit = models.TextField(null=True, blank=True)
    PreferredPaymentMethodRefListID = models.TextField(null=True, blank=True)
    PreferredPaymentMethodRefFullName = models.TextField(null=True, blank=True)
    CreditCardInfoCreditCardNumber = models.TextField(null=True, blank=True)
    CreditCardInfoExpirationMonth = models.TextField(null=True, blank=True)
    CreditCardInfoExpirationYear = models.TextField(null=True, blank=True)
    CreditCardInfoNameOnCard = models.TextField(null=True, blank=True)
    CreditCardInfoCreditCardAddress = models.TextField(null=True, blank=True)
    CreditCardInfoCreditCardPostalCode = models.TextField(null=True, blank=True)
    JobStatus = models.TextField(null=True, blank=True)
    JobStart = models.TextField(null=True, blank=True)
    JobProjectedEnd = models.TextField(null=True, blank=True)
    JobEnd = models.TextField(blank=True, null=True)
    JobDesc = models.TextField(null=True, blank=True)
    JobTypeRefListID = models.TextField(null=True, blank=True)
    JobTypeRefFullName = models.TextField(null=True, blank=True)
    Notes = models.TextField(blank=True, null=True)
    PreferredDeliveryMethod = models.TextField(null=True, blank=True)
    IsUsingCustomerTaxCode = models.TextField(null=True, blank=True)
    PriceLevelRefListID = models.TextField(null=True, blank=True)
    PriceLevelRefFullName = models.TextField(null=True, blank=True)
    ExternalGUID = models.TextField(null=True, blank=True)
    TaxRegistrationNumber = models.TextField(null=True, blank=True)
    CurrencyRefListID = models.TextField(null=True, blank=True)
    CurrencyRefFullName = models.TextField(null=True, blank=True)
    Status = models.BooleanField(default=False)


    def __str__(self):
        if self.FullName:
            return self.FullName
        else:
            return self.ListID


class Vendor(models.Model):
    ListID = models.CharField(primary_key=True, max_length=255)
    TimeCreated = models.TextField(null=True, blank=True)
    TimeModified = models.TextField(null=True, blank=True)
    EditSequence = models.TextField(null=True, blank=True)
    Name = models.TextField(null=True, blank=True)
    IsActive = models.TextField(null=True, blank=True)
    ClassRefListID = models.TextField(null=True, blank=True)
    ClassRefFullName = models.TextField(null=True, blank=True)
    IsTaxAgency = models.TextField(null=True, blank=True)
    CompanyName = models.TextField(null=True, blank=True)
    Salutation = models.TextField(null=True, blank=True)
    FirstName = models.TextField(null=True, blank=True)
    MiddleName = models.TextField(null=True, blank=True)
    LastName = models.TextField(null=True, blank=True)
    VendorAddressAddr1 = models.TextField(null=True, blank=True)
    VendorAddressAddr2 = models.TextField(null=True, blank=True)
    VendorAddressAddr3 = models.TextField(null=True, blank=True)
    VendorAddressAddr4 = models.TextField(null=True, blank=True)
    VendorAddressAddr5 = models.TextField(null=True, blank=True)
    VendorAddressCity = models.TextField(null=True, blank=True)
    VendorAddressState = models.TextField(null=True, blank=True)
    VendorAddressProvince = models.TextField(null=True, blank=True)
    VendorAddressPostalCode = models.TextField(null=True, blank=True)
    VendorAddressCountry = models.TextField(null=True, blank=True)
    VendorAddressNote = models.TextField(null=True, blank=True)
    VendorAddressBlockAddr1 = models.TextField(null=True, blank=True)
    VendorAddressBlockAddr2 = models.TextField(null=True, blank=True)
    VendorAddressBlockAddr3 = models.TextField(null=True, blank=True)
    VendorAddressBlockAddr4 = models.TextField(null=True, blank=True)
    VendorAddressBlockAddr5 = models.TextField(null=True, blank=True)
    ShipAddressAddr1 = models.TextField(null=True, blank=True)
    ShipAddressAddr2 = models.TextField(null=True, blank=True)
    ShipAddressAddr3 = models.TextField(null=True, blank=True)
    ShipAddressAddr4 = models.TextField(null=True, blank=True)
    ShipAddressAddr5 = models.TextField(null=True, blank=True)
    ShipAddressCity = models.TextField(null=True, blank=True)
    ShipAddressState = models.TextField(null=True, blank=True)
    ShipAddressPostalCode = models.TextField(null=True, blank=True)
    ShipAddressCountry = models.TextField(null=True, blank=True)
    ShipAddressNote = models.TextField(null=True, blank=True)
    Phone = models.TextField(null=True, blank=True)
    AltPhone = models.TextField(null=True, blank=True)
    Fax = models.TextField(null=True, blank=True)
    Email = models.TextField(null=True, blank=True)
    Cc = models.TextField(null=True, blank=True)
    Contact = models.TextField(null=True, blank=True)
    AltContact = models.TextField(null=True, blank=True)
    NameOnCheck = models.TextField(null=True, blank=True)
    AccountNumber = models.TextField(null=True, blank=True)
    Notes = models.TextField(null=True, blank=True)
    VendorTypeRefListID = models.TextField(null=True, blank=True)
    VendorTypeRefFullName = models.TextField(null=True, blank=True)
    TermsRefListID = models.TextField(null=True, blank=True)
    TermsRefFullName = models.TextField(null=True, blank=True)
    CreditLimit = models.TextField(null=True, blank=True)
    VendorTaxIdent = models.TextField(null=True, blank=True)
    IsVendorEligibleFor1099 = models.TextField(null=True, blank=True)
    IsVendorEligibleForT4A = models.TextField(null=True, blank=True)
    OpenBalance = models.TextField(null=True, blank=True)
    OpenBalanceDate = models.TextField(null=True, blank=True)
    Balance = models.TextField(null=True, blank=True)
    BillingRateRefListID = models.TextField(null=True, blank=True)
    BillingRateRefFullName = models.TextField(null=True, blank=True)
    PrefillAccount1RefListID = models.TextField(null=True, blank=True)
    PrefillAccount1RefFullName = models.TextField(null=True, blank=True)
    PrefillAccount2RefListID = models.TextField(null=True, blank=True)
    PrefillAccount2RefFullName = models.TextField(null=True, blank=True)
    PrefillAccount3RefListID = models.TextField(null=True, blank=True)
    PrefillAccount3RefFullName = models.TextField(null=True, blank=True)
    ExternalGUID = models.TextField(null=True, blank=True)
    BusinessNumber = models.TextField(null=True, blank=True)
    SalesTaxCodeRefListID = models.TextField(null=True, blank=True)
    SalesTaxCodeRefFullName = models.TextField(null=True, blank=True)
    SalesTaxCountry = models.TextField(null=True, blank=True)
    IsSalesTaxAgency = models.TextField(null=True, blank=True)
    SalesTaxReturnRefListID = models.TextField(null=True, blank=True)
    SalesTaxReturnRefFullName = models.TextField(null=True, blank=True)
    CurrencyRefListID = models.TextField(null=True, blank=True)
    CurrencyRefFullName = models.TextField(null=True, blank=True)
    Status = models.BooleanField(default=False)

    def __str__(self):
        return self.ListID




class SalesOrder(models.Model):
    TxnID = models.CharField(primary_key=True, max_length=255)
    TimeCreated = models.TextField(null=True, blank=True)
    TimeModified = models.TextField(null=True, blank=True)
    EditSequence = models.TextField(null=True, blank=True)
    TxnNumber = models.TextField(null=True, blank=True)
    CustomerRefListID = models.TextField(null=True, blank=True)
    CustomerRefFullName = models.TextField(null=True, blank=True)
    ClassRefListID = models.TextField(null=True, blank=True)
    ClassRefFullName = models.TextField(null=True, blank=True)
    TemplateRefListID = models.TextField(null=True, blank=True)
    TemplateRefFullName = models.TextField(null=True, blank=True)
    TxnDate = models.TextField(null=True, blank=True)
    TxnDateMacro = models.TextField(null=True, blank=True)
    RefNumber = models.TextField(null=True, blank=True)
    BillAddressAddr1 = models.TextField(null=True, blank=True)
    BillAddressAddr2 = models.TextField(null=True, blank=True)
    BillAddressAddr3 = models.TextField(null=True, blank=True)
    BillAddressAddr4 = models.TextField(null=True, blank=True)
    BillAddressAddr5 = models.TextField(null=True, blank=True)
    BillAddressCity = models.TextField(null=True, blank=True)
    BillAddressState = models.TextField(null=True, blank=True)
    BillAddressProvince = models.TextField(null=True, blank=True)
    BillAddressPostalCode = models.TextField(null=True, blank=True)
    BillAddressCountry = models.TextField(null=True, blank=True)
    BillAddressNote = models.TextField(null=True, blank=True)
    BillAddressBlockAddr1 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr2 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr3 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr4 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr5 = models.TextField(null=True, blank=True)
    ShipAddressAddr1 = models.TextField(null=True, blank=True)
    ShipAddressAddr2 = models.TextField(null=True, blank=True)
    ShipAddressAddr3 = models.TextField(null=True, blank=True)
    ShipAddressAddr4 = models.TextField(null=True, blank=True)
    ShipAddressAddr5 = models.TextField(null=True, blank=True)
    ShipAddressCity = models.TextField(null=True, blank=True)
    ShipAddressState = models.TextField(null=True, blank=True)
    ShipAddressProvince = models.TextField(null=True, blank=True)
    ShipAddressPostalCode = models.TextField(null=True, blank=True)
    ShipAddressCountry = models.TextField(null=True, blank=True)
    ShipAddressNote = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr1 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr2 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr3 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr4 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr5 = models.TextField(null=True, blank=True)
    PONumber = models.TextField(null=True, blank=True)
    TermsRefListID = models.TextField(null=True, blank=True)
    TermsRefFullName = models.TextField(null=True, blank=True)
    DueDate = models.TextField(null=True, blank=True)
    SalesRepRefListID = models.TextField(null=True, blank=True)
    SalesRepRefFullName = models.TextField(null=True, blank=True)
    FOB = models.TextField(null=True, blank=True)
    ShipDate = models.TextField(null=True, blank=True)
    ShipMethodRefListID = models.TextField(null=True, blank=True)
    ShipMethodRefFullName = models.TextField(null=True, blank=True)
    Subtotal = models.TextField(null=True, blank=True)
    ItemSalesTaxRefListID = models.TextField(null=True, blank=True)
    ItemSalesTaxRefFullName = models.TextField(null=True, blank=True)
    SalesTaxPercentage = models.TextField(null=True, blank=True)
    SalesTaxTotal = models.TextField(null=True, blank=True)
    TotalAmount = models.TextField(null=True, blank=True)
    CurrencyRefListID = models.TextField(null=True, blank=True)
    CurrencyRefFullName = models.TextField(null=True, blank=True)
    ExchangeRate = models.TextField(null=True, blank=True)
    TotalAmountInHomeCurrency = models.TextField(null=True, blank=True)
    IsManuallyClosed = models.TextField(null=True, blank=True)
    IsFullyInvoiced = models.TextField(null=True, blank=True)
    Memo = models.TextField(null=True, blank=True)
    CustomerMsgRefListID = models.TextField(null=True, blank=True)
    CustomerMsgRefFullName = models.TextField(null=True, blank=True)
    IsToBePrinted = models.TextField(null=True, blank=True)
    IsToBeEmailed = models.TextField(null=True, blank=True)
    IsTaxIncluded = models.TextField(null=True, blank=True)
    CustomerSalesTaxCodeRefListID = models.TextField(null=True, blank=True)
    CustomerSalesTaxCodeRefFullName = models.TextField(null=True, blank=True)
    CustomerTaxCodeRefListID = models.TextField(null=True, blank=True)
    CustomFieldOther = models.TextField(null=True, blank=True)
    Tax1Total = models.TextField(null=True, blank=True)
    Tax2Total = models.TextField(null=True, blank=True)
    AmountIncludesVAT = models.TextField(null=True, blank=True)
    Status = models.BooleanField(default=False)

    def __str__(self):
        return self.TxnID


class SalesOrderItems(models.Model):
    TxnID = models.CharField(primary_key=True, max_length=255)
    ItemListID = models.TextField(null=True, blank=True)
    ItemFullName = models.TextField(null=True, blank=True)
    Desc = models.TextField(null=True, blank=True)
    Quantity = models.TextField(null=True, blank=True)
    Amount = models.TextField(null=True, blank=True)
    TaxAmount = models.TextField(null=True, blank=True)
    UnitofMeasure = models.TextField(null=True, blank=True)
    TxnLineId = models.TextField(null=True, blank=True)
    Invoice = models.TextField(null=True, blank=True)
    Type = models.TextField(null=True, blank=True)
    Status = models.BooleanField(default=False)


    def __str__(self):
        return self.TxnID


class PurchaseOrder(models.Model):
    TxnID = models.CharField(max_length=255, primary_key=True)
    TimeCreated = models.TextField(null=True, blank=True)
    TimeModified = models.TextField(null=True, blank=True)
    EditSequence = models.TextField(null=True, blank=True)
    TxnNumber = models.TextField(null=True, blank=True)
    VendorRefListID = models.TextField(null=True, blank=True)
    VendorRefFullName = models.TextField(null=True, blank=True)
    ClassRefListID = models.TextField(null=True, blank=True)
    ClassRefFullName = models.TextField(null=True, blank=True)
    InventorySiteRefListID = models.TextField(null=True, blank=True)
    InventorySiteRefFullName = models.TextField(null=True, blank=True)
    ShipToEntityRefListID = models.TextField(null=True, blank=True)
    ShipToEntityRefFullName = models.TextField(null=True, blank=True)
    TemplateRefListID = models.TextField(null=True, blank=True)
    TemplateRefFullName = models.TextField(null=True, blank=True)
    TxnDate = models.TextField(null=True, blank=True)
    TxnDateMacro = models.TextField(null=True, blank=True)
    RefNumber = models.TextField(null=True, blank=True)
    VendorAddressAddr1 = models.TextField(null=True, blank=True)
    VendorAddressAddr2 = models.TextField(null=True, blank=True)
    VendorAddressAddr3 = models.TextField(null=True, blank=True)
    VendorAddressAddr4 = models.TextField(null=True, blank=True)
    VendorAddressAddr5 = models.TextField(null=True, blank=True)
    VendorAddressCity = models.TextField(null=True, blank=True)
    VendorAddressState = models.TextField(null=True, blank=True)
    VendorAddressProvince = models.TextField(null=True, blank=True)
    VendorAddressCounty = models.TextField(null=True, blank=True)
    VendorAddressPostalCode = models.TextField(null=True, blank=True)
    VendorAddressCountry = models.TextField(null=True, blank=True)
    VendorAddressNote = models.TextField(null=True, blank=True)
    VendorAddressBlockAddr1 = models.TextField(null=True, blank=True)
    VendorAddressBlockAddr2 = models.TextField(null=True, blank=True)
    VendorAddressBlockAddr3 = models.TextField(null=True, blank=True)
    VendorAddressBlockAddr4 = models.TextField(null=True, blank=True)
    VendorAddressBlockAddr5 = models.TextField(null=True, blank=True)
    ShipAddressAddr1 = models.TextField(null=True, blank=True)
    ShipAddressAddr2 = models.TextField(null=True, blank=True)
    ShipAddressAddr3 = models.TextField(null=True, blank=True)
    ShipAddressAddr4 = models.TextField(null=True, blank=True)
    ShipAddressAddr5 = models.TextField(null=True, blank=True)
    ShipAddressCity = models.TextField(null=True, blank=True)
    ShipAddressState = models.TextField(null=True, blank=True)
    ShipAddressProvince = models.TextField(null=True, blank=True)
    ShipAddressCounty = models.TextField(null=True, blank=True)
    ShipAddressPostalCode = models.TextField(null=True, blank=True)
    ShipAddressCountry = models.TextField(null=True, blank=True)
    ShipAddressNote = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr1 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr2 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr3 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr4 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr5 = models.TextField(null=True, blank=True)
    TermsRefListID = models.TextField(null=True, blank=True)
    TermsRefFullName = models.TextField(null=True, blank=True)
    DueDate = models.TextField(null=True, blank=True)
    ExpectedDate = models.TextField(null=True, blank=True)
    ShipMethodRefListID = models.TextField(null=True, blank=True)
    ShipMethodRefFullName = models.TextField(null=True, blank=True)
    FOB = models.TextField(null=True, blank=True)
    TotalAmount = models.TextField(null=True, blank=True)
    CurrencyRefListID = models.TextField(null=True, blank=True)
    CurrencyRefFullName = models.TextField(null=True, blank=True)
    ExchangeRate = models.TextField(null=True, blank=True)
    TotalAmountInHomeCurrency = models.TextField(null=True, blank=True)
    IsManuallyClosed = models.TextField(null=True, blank=True)
    IsFullyReceived = models.TextField(null=True, blank=True)
    Memo = models.TextField(null=True, blank=True)
    VendorMsg = models.TextField(null=True, blank=True)
    IsToBePrinted = models.TextField(null=True, blank=True)
    IsToBeEmailed = models.TextField(null=True, blank=True)
    IsTaxIncluded = models.TextField(null=True, blank=True)
    SalesTaxCodeRefListID = models.TextField(null=True, blank=True)
    SalesTaxCodeRefFullName = models.TextField(null=True, blank=True)
    TaxCodeRefListID = models.TextField(null=True, blank=True)
    TaxCodeRefFullName = models.TextField(null=True, blank=True)
    CustomFieldOther1 = models.TextField(null=True, blank=True)
    CustomFieldOther2 = models.TextField(null=True, blank=True)
    Tax1Total = models.TextField(null=True, blank=True)
    Tax2Total = models.TextField(null=True, blank=True)
    AmountIncludesVAT = models.TextField(null=True, blank=True)
    Status = models.BooleanField(default=False)

    def __str__(self):
        return self.TxnID



class PurchaseOrderItems(models.Model):
    TxnID = models.TextField(primary_key=True)
    ItemListID = models.TextField(null=True, blank=True)
    ItemFullName = models.TextField(null=True, blank=True)
    Desc = models.TextField(null=True, blank=True)
    Quantity = models.TextField(null=True, blank=True)
    Amount = models.TextField(null=True, blank=True)
    TaxAmount = models.TextField(null=True, blank=True)
    UnitofMeasure = models.TextField(null=True, blank=True)
    TxnLineId = models.TextField(null=True, blank=True)
    Type = models.TextField(null=True, blank=True)
    CustomerListID = models.TextField(null=True, blank=True)
    CustomerFullName = models.TextField(null=True, blank=True)
    Status = models.BooleanField(default=False)


    def __str__(self):
        return self.TxnID


class ItemInventory(models.Model):
    ListID = models.TextField(primary_key=True)
    TimeCreated = models.TextField(null=True, blank=True)
    TimeModified = models.TextField(null=True, blank=True)
    EditSequence = models.TextField(null=True, blank=True)
    Name = models.TextField(null=True, blank=True)
    FullName = models.TextField(null=True, blank=True)
    BarCodeValue = models.TextField(null=True, blank=True)
    BarCodeAssignEvenIfUsed = models.TextField(null=True, blank=True)
    BarCodeAllowOverride = models.TextField(null=True, blank=True)
    IsActive = models.TextField(null=True, blank=True)
    ClassRefListID = models.TextField(null=True, blank=True)
    ClassRefFullName = models.TextField(null=True, blank=True)
    ParentRefListID = models.TextField(null=True, blank=True)
    ParentRefFullName = models.TextField(null=True, blank=True)
    Sublevel = models.TextField(null=True, blank=True)
    ManufacturerPartNumber = models.TextField(null=True, blank=True)
    UnitOfMeasureSetRefListID = models.TextField(null=True, blank=True)
    UnitOfMeasureSetRefFullName = models.TextField(null=True, blank=True)
    ForceUOMChange = models.TextField(null=True, blank=True)
    SalesTaxCodeRefListID = models.TextField(null=True, blank=True)
    SalesTaxCodeRefFullName = models.TextField(null=True, blank=True)
    SalesDesc = models.TextField(null=True, blank=True)
    SalesPrice = models.TextField(null=True, blank=True)
    IncomeAccountRefListID = models.TextField(null=True, blank=True)
    IncomeAccountRefFullName = models.TextField(null=True, blank=True)
    ApplyIncomeAccountRefToExistingTxns = models.TextField(null=True, blank=True)
    PurchaseDesc = models.TextField(null=True, blank=True)
    PurchaseCost = models.TextField(null=True, blank=True)
    COGSAccountRefListID = models.TextField(null=True, blank=True)
    COGSAccountRefFullName = models.TextField(null=True, blank=True)
    PrefVendorRefListID = models.TextField(null=True, blank=True)
    PrefVendorRefFullName = models.TextField(null=True, blank=True)
    AssetAccountRefListID = models.TextField(null=True, blank=True)
    AssetAccountRefFullName = models.TextField(null=True, blank=True)
    ReorderPoint = models.TextField(null=True, blank=True)
    Maximum = models.TextField(null=True, blank=True)
    QuantityOnHand = models.TextField(null=True, blank=True)
    TotalValue = models.TextField(null=True, blank=True)
    InventoryDate = models.TextField(null=True, blank=True)
    AverageCost = models.TextField(null=True, blank=True)
    QuantityOnOrder = models.TextField(null=True, blank=True)
    QuantityOnSalesOrder = models.TextField(null=True, blank=True)
    ExternalGUID = models.TextField(null=True, blank=True)
    Status = models.BooleanField(default=False)

    
    def __str__(self):
        return self.ListID
   

class Invoice(models.Model):
    TxnID = models.TextField(primary_key=True)
    TimeCreated = models.TextField(null=True, blank=True)
    TimeModified = models.TextField(null=True, blank=True)
    EditSequence = models.TextField(null=True, blank=True)
    TxnNumber = models.TextField(null=True, blank=True)
    CustomerRefListID = models.TextField(null=True, blank=True)
    CustomerRefFullName = models.TextField(null=True, blank=True)
    ClassRefListID = models.TextField(null=True, blank=True)
    ClassRefFullName = models.TextField(null=True, blank=True)
    ARAccountRefListID = models.TextField(null=True, blank=True)
    ARAccountRefFullName = models.TextField(null=True, blank=True)
    TemplateRefListID = models.TextField(null=True, blank=True)
    TemplateRefFullName = models.TextField(null=True, blank=True)
    TxnDate = models.TextField(null=True, blank=True)
    TxnDateMacro = models.TextField(null=True, blank=True)
    RefNumber = models.TextField(null=True, blank=True)
    BillAddressAddr1 = models.TextField(null=True, blank=True)
    BillAddressAddr2 = models.TextField(null=True, blank=True)
    BillAddressAddr3 = models.TextField(null=True, blank=True)
    BillAddressAddr4 = models.TextField(null=True, blank=True)
    BillAddressAddr5 = models.TextField(null=True, blank=True)
    BillAddressCity = models.TextField(null=True, blank=True)
    BillAddressState = models.TextField(null=True, blank=True)
    BillAddressProvince = models.TextField(null=True, blank=True)
    BillAddressPostalCode = models.TextField(null=True, blank=True)
    BillAddressCountry = models.TextField(null=True, blank=True)
    BillAddressNote = models.TextField(null=True, blank=True)
    BillAddressBlockAddr1 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr2 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr3 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr4 = models.TextField(null=True, blank=True)
    BillAddressBlockAddr5 = models.TextField(null=True, blank=True)
    ShipAddressAddr1 = models.TextField(null=True, blank=True)
    ShipAddressAddr2 = models.TextField(null=True, blank=True)
    ShipAddressAddr3 = models.TextField(null=True, blank=True)
    ShipAddressAddr4 = models.TextField(null=True, blank=True)
    ShipAddressAddr5 = models.TextField(null=True, blank=True)
    ShipAddressCity = models.TextField(null=True, blank=True)
    ShipAddressState = models.TextField(null=True, blank=True)
    ShipAddressProvince = models.TextField(null=True, blank=True)
    ShipAddressPostalCode = models.TextField(null=True, blank=True)
    ShipAddressCountry = models.TextField(null=True, blank=True)
    ShipAddressNote = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr1 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr2 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr3 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr4 = models.TextField(null=True, blank=True)
    ShipAddressBlockAddr5 = models.TextField(null=True, blank=True)
    IsPending = models.TextField(null=True, blank=True)
    IsFinanceCharge = models.TextField(null=True, blank=True)
    PONumber = models.TextField(null=True, blank=True)
    TermsRefListID = models.TextField(null=True, blank=True)
    TermsRefFullName = models.TextField(null=True, blank=True)
    DueDate = models.TextField(null=True, blank=True)
    SalesRepRefListID = models.TextField(null=True, blank=True)
    SalesRepRefFullName = models.TextField(null=True, blank=True)
    FOB = models.TextField(null=True, blank=True)
    ShipDate = models.TextField(null=True, blank=True)
    ShipMethodRefListID = models.TextField(null=True, blank=True)
    ShipMethodRefFullName = models.TextField(null=True, blank=True)
    Subtotal = models.TextField(null=True, blank=True)
    ItemSalesTaxRefListID = models.TextField(null=True, blank=True)
    ItemSalesTaxRefFullName = models.TextField(null=True, blank=True)
    SalesTaxPercentage = models.TextField(null=True, blank=True)
    SalesTaxTotal = models.TextField(null=True, blank=True)
    AppliedAmount = models.TextField(null=True, blank=True)
    BalanceRemaining = models.TextField(null=True, blank=True)
    CurrencyRefListID = models.TextField(null=True, blank=True)
    CurrencyRefFullName = models.TextField(null=True, blank=True)
    ExchangeRate = models.TextField(null=True, blank=True)
    BalanceRemainingInHomeCurrency = models.TextField(null=True, blank=True)
    Memo = models.TextField(null=True, blank=True)
    IsPaid = models.TextField(null=True, blank=True)
    CustomerMsgRefListID = models.TextField(null=True, blank=True)
    CustomerMsgRefFullName = models.TextField(null=True, blank=True)
    IsToBePrinted = models.TextField(null=True, blank=True)
    IsToBeEmailed = models.TextField(null=True, blank=True)
    IsTaxIncluded = models.TextField(null=True, blank=True)
    CustomerSalesTaxCodeRefListID = models.TextField(null=True, blank=True)
    CustomerSalesTaxCodeRefFullName = models.TextField(null=True, blank=True)
    CustomerTaxCodeRefListID = models.TextField(null=True, blank=True)
    SuggestedDiscountAmount = models.TextField(null=True, blank=True)
    SuggestedDiscountDate = models.TextField(null=True, blank=True)
    CustomFieldOther = models.TextField(null=True, blank=True)
    LinkToTxnID1 = models.TextField(null=True, blank=True)
    Tax1Total = models.TextField(null=True, blank=True)
    Tax2Total = models.TextField(null=True, blank=True)
    AmountIncludesVAT = models.TextField(null=True, blank=True)
    DueDays = models.TextField(null=True, blank=True)
    Status = models.BooleanField(default=False)


    def __str__(self):
        return self.TxnID


class ShipAddress(models.Model):
    ListID = models.TextField(null=True, blank=True)
    ShipAddress = models.TextField(null=True, blank=True)
    Category = models.TextField(null=True, blank=True)
    Address = models.TextField(null=True, blank=True)
    Note = models.TextField(null=True, blank=True)
    Country = models.TextField(null=True, blank=True)
    City = models.TextField(null=True, blank=True)
    PostalCode = models.TextField(null=True, blank=True)
    State = models.TextField(null=True, blank=True)
    Status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.ShipAddress} ({self.Category})"