# Generated by Django 4.1.6 on 2023-02-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_salesorder_customer_status_alter_customer_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderItems',
            fields=[
                ('TxnID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ItemListID', models.CharField(blank=True, max_length=255, null=True)),
                ('ItemFullName', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('Amount', models.CharField(blank=True, max_length=255, null=True)),
                ('TaxAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('UnitofMeasure', models.CharField(blank=True, max_length=255, null=True)),
                ('TxnLineId', models.CharField(blank=True, max_length=255, null=True)),
                ('Invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='salesorder',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
