# Generated by Django 4.1.6 on 2023-02-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_purchaseorder_amountincludesvat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('ListID', models.TextField(primary_key=True, serialize=False)),
                ('TimeCreated', models.TextField(blank=True, null=True)),
                ('TimeModified', models.TextField(blank=True, null=True)),
                ('EditSequence', models.TextField(blank=True, null=True)),
                ('Name', models.TextField(blank=True, null=True)),
                ('FullName', models.TextField(blank=True, null=True)),
                ('BarCodeValue', models.TextField(blank=True, null=True)),
                ('BarCodeAssignEvenIfUsed', models.TextField(blank=True, null=True)),
                ('BarCodeAllowOverride', models.TextField(blank=True, null=True)),
                ('IsActive', models.TextField(blank=True, null=True)),
                ('ClassRefListID', models.TextField(blank=True, null=True)),
                ('ClassRefFullName', models.TextField(blank=True, null=True)),
                ('ParentRefListID', models.TextField(blank=True, null=True)),
                ('ParentRefFullName', models.TextField(blank=True, null=True)),
                ('Sublevel', models.TextField(blank=True, null=True)),
                ('ManufacturerPartNumber', models.TextField(blank=True, null=True)),
                ('UnitOfMeasureSetRefListID', models.TextField(blank=True, null=True)),
                ('UnitOfMeasureSetRefFullName', models.TextField(blank=True, null=True)),
                ('ForceUOMChange', models.TextField(blank=True, null=True)),
                ('SalesTaxCodeRefListID', models.TextField(blank=True, null=True)),
                ('SalesTaxCodeRefFullName', models.TextField(blank=True, null=True)),
                ('SalesDesc', models.TextField(blank=True, null=True)),
                ('SalesPrice', models.TextField(blank=True, null=True)),
                ('IncomeAccountRefListID', models.TextField(blank=True, null=True)),
                ('IncomeAccountRefFullName', models.TextField(blank=True, null=True)),
                ('ApplyIncomeAccountRefToExistingTxns', models.TextField(blank=True, null=True)),
                ('PurchaseDesc', models.TextField(blank=True, null=True)),
                ('PurchaseCost', models.TextField(blank=True, null=True)),
                ('COGSAccountRefListID', models.TextField(blank=True, null=True)),
                ('COGSAccountRefFullName', models.TextField(blank=True, null=True)),
                ('PrefVendorRefListID', models.TextField(blank=True, null=True)),
                ('PrefVendorRefFullName', models.TextField(blank=True, null=True)),
                ('AssetAccountRefListID', models.TextField(blank=True, null=True)),
                ('AssetAccountRefFullName', models.TextField(blank=True, null=True)),
                ('ReorderPoint', models.TextField(blank=True, null=True)),
                ('Maximum', models.TextField(blank=True, null=True)),
                ('QuantityOnHand', models.TextField(blank=True, null=True)),
                ('TotalValue', models.TextField(blank=True, null=True)),
                ('InventoryDate', models.TextField(blank=True, null=True)),
                ('AverageCost', models.TextField(blank=True, null=True)),
                ('QuantityOnOrder', models.TextField(blank=True, null=True)),
                ('QuantityOnSalesOrder', models.TextField(blank=True, null=True)),
                ('ExternalGUID', models.TextField(blank=True, null=True)),
                ('CrudStatus', models.TextField(blank=True, null=True)),
                ('SyncStatus', models.TextField(blank=True, null=True)),
                ('ModifiedTimeLocal', models.TextField(blank=True, null=True)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('TxnID', models.TextField(primary_key=True, serialize=False)),
                ('ItemListID', models.TextField(blank=True, null=True)),
                ('ItemFullName', models.TextField(blank=True, null=True)),
                ('Desc', models.TextField(blank=True, null=True)),
                ('Quantity', models.TextField(blank=True, null=True)),
                ('Amount', models.TextField(blank=True, null=True)),
                ('TaxAmount', models.TextField(blank=True, null=True)),
                ('UnitofMeasure', models.TextField(blank=True, null=True)),
                ('TxnLineId', models.TextField(blank=True, null=True)),
                ('Type', models.TextField(blank=True, null=True)),
                ('CustomerListID', models.TextField(blank=True, null=True)),
                ('CustomerFullName', models.TextField(blank=True, null=True)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
