# Generated by Django 4.1.6 on 2023-02-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CrudStatus',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ModifiedTimeLocal',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='SyncStatus',
        ),
        migrations.RemoveField(
            model_name='iteminventory',
            name='CrudStatus',
        ),
        migrations.RemoveField(
            model_name='iteminventory',
            name='ModifiedTimeLocal',
        ),
        migrations.RemoveField(
            model_name='iteminventory',
            name='SyncStatus',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='CrudStatus',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='ModifiedTimeLocal',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='SyncStatus',
        ),
    ]
