# Generated by Django 4.1.6 on 2023-02-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_remove_customer_crudstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='BillAddressCounty',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ShipAddressCounty',
        ),
    ]
