# Generated by Django 4.1.6 on 2023-02-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_invoice_billaddresscounty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Balance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='AccountNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='AltContact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='AltPhone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Balance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressBlockAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressBlockAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressBlockAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressBlockAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressBlockAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressCountry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressPostalCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressProvince',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BillAddressState',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='BusinessNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CompanyName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CreditCardInfoCreditCardAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CreditCardInfoCreditCardNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CreditCardInfoCreditCardPostalCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CreditCardInfoExpirationMonth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CreditCardInfoExpirationYear',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CreditCardInfoNameOnCard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CreditLimit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CurrencyRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CurrencyRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustomerTypeRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustomerTypeRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='EditSequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ExternalGUID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Fax',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='FirstName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='FullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='IsActive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='IsUsingCustomerTaxCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ItemSalesTaxRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ItemSalesTaxRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='JobDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='JobProjectedEnd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='JobStart',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='JobStatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='JobTitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='JobTypeRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='JobTypeRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='LastName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='MiddleName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='OpenBalance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PreferredDeliveryMethod',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PreferredPaymentMethodRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PreferredPaymentMethodRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PriceLevelRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PriceLevelRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ResaleNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='SalesRepRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='SalesRepRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='SalesTaxCodeRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='SalesTaxCodeRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='SalesTaxCountry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Salutation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressBlockAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressBlockAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressBlockAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressBlockAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressBlockAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressCountry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressPostalCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressProvince',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ShipAddressState',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TaxCodeRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TaxCodeRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TaxRegistrationNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TermsRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TermsRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TotalBalance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ClassRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ClassRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='DueDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='EditSequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ExpectedDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='InventorySiteRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='InventorySiteRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='RefNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressBlockAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressBlockAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressBlockAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressBlockAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressBlockAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressCountry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressCounty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressPostalCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressProvince',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipAddressState',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipMethodRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipToEntityRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ShipToEntityRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='TemplateRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='TemplateRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='TermsRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='TermsRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='TimeCreated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='TimeModified',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='TxnDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='TxnDateMacro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='TxnNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressBlockAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressBlockAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressBlockAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressBlockAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressBlockAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressCountry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressCounty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressPostalCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressProvince',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorAddressState',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='VendorRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='AmountIncludesVAT',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressBlockAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressBlockAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressBlockAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressBlockAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressBlockAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressCountry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressPostalCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressProvince',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillAddressState',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ClassRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ClassRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='CurrencyRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='CurrencyRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='CustomFieldOther',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='CustomerMsgRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='CustomerMsgRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='CustomerRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='CustomerRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='CustomerSalesTaxCodeRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='CustomerSalesTaxCodeRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='CustomerTaxCodeRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='DueDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='EditSequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ExchangeRate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='FOB',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='IsFullyInvoiced',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='IsManuallyClosed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='IsTaxIncluded',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='IsToBeEmailed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='IsToBePrinted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ItemSalesTaxRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ItemSalesTaxRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='Memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='PONumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='RefNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='SalesRepRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='SalesRepRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='SalesTaxPercentage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='SalesTaxTotal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressBlockAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressBlockAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressBlockAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressBlockAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressBlockAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressCountry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressPostalCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressProvince',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipAddressState',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipMethodRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ShipMethodRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='Subtotal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='Tax1Total',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='Tax2Total',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TemplateRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TemplateRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TermsRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TermsRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TimeCreated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TimeModified',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TotalAmount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TotalAmountInHomeCurrency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TxnDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TxnDateMacro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TxnNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitems',
            name='Amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitems',
            name='Invoice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitems',
            name='ItemFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitems',
            name='ItemListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitems',
            name='Quantity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitems',
            name='TaxAmount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitems',
            name='TxnLineId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitems',
            name='Type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitems',
            name='UnitofMeasure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='AccountNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='AltContact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='AltPhone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='BillingRateRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='BillingRateRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='BusinessNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Cc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ClassRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ClassRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='CompanyName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='CreditLimit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='CurrencyRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='CurrencyRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='EditSequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ExternalGUID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Fax',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='FirstName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='IsActive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='IsSalesTaxAgency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='IsTaxAgency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='IsVendorEligibleFor1099',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='IsVendorEligibleForT4A',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='LastName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='MiddleName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='NameOnCheck',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='OpenBalance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='OpenBalanceDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PrefillAccount1RefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PrefillAccount1RefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PrefillAccount2RefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PrefillAccount2RefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PrefillAccount3RefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PrefillAccount3RefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='SalesTaxCodeRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='SalesTaxCodeRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='SalesTaxCountry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='SalesTaxReturnRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='SalesTaxReturnRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Salutation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ShipAddressAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ShipAddressAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ShipAddressAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ShipAddressAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ShipAddressAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ShipAddressCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ShipAddressCountry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ShipAddressNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ShipAddressPostalCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ShipAddressState',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='TermsRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='TermsRefListID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='TimeCreated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='TimeModified',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressBlockAddr1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressBlockAddr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressBlockAddr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressBlockAddr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressBlockAddr5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressCountry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressPostalCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressProvince',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorAddressState',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorTaxIdent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorTypeRefFullName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorTypeRefListID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
