# Generated by Django 4.1.6 on 2023-02-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_vendor_balance_alter_customer_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TimeCreated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TimeModified',
            field=models.TextField(blank=True, null=True),
        ),
    ]
