# Generated by Django 4.1.6 on 2023-03-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_shipaddress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipaddress',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipaddress',
            name='City',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipaddress',
            name='Country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipaddress',
            name='Note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipaddress',
            name='PostalCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipaddress',
            name='State',
            field=models.TextField(blank=True, null=True),
        ),
    ]
