# Generated by Django 4.1.6 on 2023-03-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_shipaddress_address_shipaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='DueDays',
            field=models.TextField(blank=True, null=True),
        ),
    ]
